################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
P_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
JMP_UPPER_DEPS := 
PP_DEPS := 
SX_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
SREC := 
S_UPPER_DEPS := 
MAP := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ra/aws/FreeRTOS/FreeRTOS/Source \
ra/board/ra8e1_fpb \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/bsp/mcu/ra8e1 \
ra/fsp/src/r_ioport \
ra/fsp/src/rm_freertos_port \
ra_gen \
src/graph/stream_nodes/arm/amplifier \
src/graph/stream_nodes/arm/anr \
src/graph/stream_nodes/arm/demodulator \
src/graph/stream_nodes/arm/filter \
src/graph/stream_nodes/arm/filter2D \
src/graph/stream_nodes/arm/fixedbf \
src/graph/stream_nodes/arm/modulator \
src/graph/stream_nodes/arm/router \
src/graph/stream_nodes/arm/script \
src/graph/stream_nodes/bitbank/JPEGENC \
src/graph/stream_nodes/elm-lang/TJpgDec \
src/graph/stream_nodes/signal-processingFR/compressor \
src/graph/stream_nodes/signal-processingFR/decompressor \
src/graph/stream_nodes/signal-processingFR/detector \
src/graph/stream_nodes/signal-processingFR/detector2D \
src/graph/stream_nodes/signal-processingFR/kws \
src/graph/stream_nodes/signal-processingFR/resampler \
src/graph/stream_platform/platform_services \
src/graph/stream_platform/platform_services/stream_libraries/CMSIS-DSP/Source/FilteringFunctions \
src/graph/stream_platform/platform_services/stream_libraries/standard_library \
src/graph/stream_platform/ra8e1 \
src/graph/stream_platform/ra8e1/stream_libraries/CMSIS-DSP/Source/CommonTables \
src/graph/stream_platform/ra8e1/stream_libraries/CMSIS-DSP/Source/FilteringFunctions \
src/graph/stream_src \
src \

